import {
  Activity,
  BadgeCheck,
  Bed,
  CalendarCheck2,
  ClipboardCheck,
  ClipboardList,
  Droplets,
  Dumbbell,
  FileText,
  Flower2,
  HeartPulse,
  Hospital,
  Leaf,
  Microscope,
  ScanLine,
  ShieldCheck,
  Smile,
  Sparkles,
  Stethoscope,
  SunMedium,
  TestTube2,
  UserRoundCheck,
  Waves,
} from 'lucide-react';

const sharedJourney = [
  { title: 'Connect', copy: 'Use call or WhatsApp to request a convenient appointment time.', icon: CalendarCheck2 },
  { title: 'Share', copy: 'Provide basic context so the visit can start with clarity.', icon: ClipboardList },
  { title: 'Visit', copy: 'Arrive for a calm, guided experience with clear communication.', icon: UserRoundCheck },
  { title: 'Next steps', copy: 'Leave with simple follow-up information for your care conversation.', icon: BadgeCheck },
];

export const dentistConfig = {
  shortLabel: 'Dental',
  businessType: 'dentist',
  businessLabel: 'dental concept',
  navIcon: Smile,
  heroIcon: Smile,
  miniIcon: CalendarCheck2,
  miniLabel: 'Easy booking',
  appointmentTitle: 'Request a consult',
  visualLabel: 'Dental Studio',
  colors: { accent: '#22d3ee', soft: '#ecfeff', strong: '#0e7490', glow: 'rgba(125, 211, 252, 0.48)' },
  heroTitlePrefix: 'Premium dental care concept for a',
  heroTitleAccent: 'calmer patient journey.',
  heroCopy: clinic => `${clinic.clinicName} is framed as a polished design preview for dental outreach in ${clinic.city}, with simple contact paths and reassuring visit guidance.`,
  heroBadges: ['Calm first-visit experience', 'Clear appointment guidance', 'Transparent next steps'],
  visualCards: ['Comfort-led appointment flow', 'Dental care sections with measured copy', 'Mobile-first call and WhatsApp actions'],
  servicesTitle: 'Dental website sections that feel refined, useful, and calm.',
  servicesCopy: 'A premium layout for common dental-care conversations without promising outcomes or inventing credentials.',
  services: [
    { title: 'Preventive visits', description: 'Helpful framing for routine checkups and hygiene conversations.', icon: ShieldCheck },
    { title: 'Smile consultation', description: 'A soft, clear way to introduce care planning conversations.', icon: Smile },
    { title: 'Appointment flow', description: 'Visible contact actions designed for quick mobile inquiries.', icon: CalendarCheck2 },
    { title: 'Comfort-first studio', description: 'Premium visual cues that make the experience feel calm.', icon: Sparkles },
  ],
  trustTitle: 'Credibility built through clarity, not inflated numbers.',
  trustCopy: 'Trust cues describe the page experience itself and avoid ratings, outcomes, awards, or patient-volume claims.',
  trustCards: [
    { kicker: 'Clarity', title: 'Simple decision paths', copy: 'Visitors can understand how to contact the clinic without pressure.' },
    { kicker: 'Tone', title: 'Measured healthcare copy', copy: 'Language stays warm while avoiding unrealistic treatment claims.' },
    { kicker: 'Access', title: 'Mobile-ready contact', copy: 'Call and WhatsApp actions are easy to find on every screen size.' },
  ],
  journeyTitle: 'A thoughtful path from first contact to follow-up.',
  journeyCopy: 'Simple steps designed for comfort and clarity, with a polished clinic experience.',
  journey: sharedJourney,
  ctaTitle: 'Ready to preview a premium dental inquiry experience?',
  ctaCopy: clinic => `This sample section keeps outreach direct with prominent contact actions for ${clinic.clinicName} in ${clinic.city}.`,
};

export const dermatologyConfig = {
  shortLabel: 'Derma',
  businessType: 'dermatologist',
  businessLabel: 'dermatology concept',
  navIcon: Sparkles,
  heroIcon: Sparkles,
  miniIcon: Droplets,
  miniLabel: 'Skin consult',
  appointmentTitle: 'Plan a skin visit',
  visualLabel: 'Dermatology',
  colors: { accent: '#c084fc', soft: '#faf5ff', strong: '#7e22ce', glow: 'rgba(216, 180, 254, 0.46)' },
  heroTitlePrefix: 'Modern dermatology website concept for',
  heroTitleAccent: 'clearer skin-care conversations.',
  heroCopy: clinic => `${clinic.clinicName} is presented as a premium dermatology design preview for ${clinic.city}, focused on clear consultation pathways and calm patient education.`,
  heroBadges: ['Skin consultation framing', 'Clean visual hierarchy', 'Sample-safe patient guidance'],
  visualCards: ['Elegant skin-care service cards', 'Soft lavender visual system', 'Clear consultation CTA structure'],
  servicesTitle: 'A polished dermatology layout with a calm editorial feel.',
  servicesCopy: 'Service areas are framed as consultation topics, avoiding before-and-after promises or outcome claims.',
  services: [
    { title: 'Skin consultation', description: 'A clear entry point for visitors exploring dermatologist-led guidance.', icon: Sparkles },
    { title: 'Acne conversation', description: 'Measured copy for discussing concerns without promising results.', icon: Droplets },
    { title: 'Hair and scalp visit', description: 'Structured content for appointment-led hair and scalp inquiries.', icon: ScanLine },
    { title: 'Routine skin checks', description: 'A simple, calm way to guide preventive skin-care visits.', icon: ShieldCheck },
  ],
  trustTitle: 'A trustworthy tone for sensitive skin-care decisions.',
  trustCopy: 'The template emphasizes clarity, discretion, and careful language instead of dramatic transformations.',
  trustCards: [
    { kicker: 'Discretion', title: 'Private, calm tone', copy: 'The design avoids sensational visuals and keeps the experience composed.' },
    { kicker: 'Education', title: 'Clear service framing', copy: 'Visitors see consultation topics without medical overpromising.' },
    { kicker: 'Flow', title: 'Easy contact actions', copy: 'Prominent CTAs support quick inquiry without feeling aggressive.' },
  ],
  journeyTitle: 'A calm path from concern to consultation.',
  journeyCopy: 'The patient journey is designed for sensitive, question-led dermatology browsing.',
  journey: sharedJourney,
  ctaTitle: 'Create a calmer dermatology inquiry experience.',
  ctaCopy: clinic => `Use this sample CTA style for ${clinic.clinicName} to make consultation inquiries feel simple and respectful.`,
};

export const physioConfig = {
  shortLabel: 'Physio',
  businessType: 'physiotherapy',
  businessLabel: 'physiotherapy concept',
  navIcon: Dumbbell,
  heroIcon: Activity,
  miniIcon: Activity,
  miniLabel: 'Movement plan',
  appointmentTitle: 'Request a session',
  visualLabel: 'Physiotherapy',
  colors: { accent: '#34d399', soft: '#ecfdf5', strong: '#047857', glow: 'rgba(110, 231, 183, 0.46)' },
  heroTitlePrefix: 'Premium physiotherapy concept for',
  heroTitleAccent: 'clearer movement support.',
  heroCopy: clinic => `${clinic.clinicName} is shaped as a clean physiotherapy preview for ${clinic.city}, with approachable visit planning and practical recovery-focused content.`,
  heroBadges: ['Movement-led visit flow', 'Clear session guidance', 'Supportive recovery tone'],
  visualCards: ['Movement-focused service sections', 'Clean recovery pathway', 'Fast call and WhatsApp actions'],
  servicesTitle: 'Physiotherapy sections with movement, clarity, and care.',
  servicesCopy: 'Copy is framed around support and guidance without claiming recovery guarantees.',
  services: [
    { title: 'Pain consultation', description: 'A structured entry point for people exploring physio support.', icon: Activity },
    { title: 'Mobility sessions', description: 'Friendly content for movement and flexibility-focused appointments.', icon: Waves },
    { title: 'Posture support', description: 'Clear explanations for posture and workplace-related concerns.', icon: Dumbbell },
    { title: 'Follow-up plans', description: 'Simple next-step communication for ongoing physiotherapy visits.', icon: ClipboardCheck },
  ],
  trustTitle: 'Supportive design for recovery-focused browsing.',
  trustCopy: 'The template feels confident without promising timelines, outcomes, or recovery results.',
  trustCards: [
    { kicker: 'Support', title: 'Guided next steps', copy: 'Visitors can see how the first session might be requested.' },
    { kicker: 'Comfort', title: 'Non-intimidating visuals', copy: 'The interface feels active but not clinical or harsh.' },
    { kicker: 'Clarity', title: 'Plain-language sections', copy: 'Service cards keep browsing practical and easy to scan.' },
  ],
  journeyTitle: 'A practical path from inquiry to guided movement.',
  journeyCopy: 'A mobile-friendly structure for visitors looking for physiotherapy support.',
  journey: sharedJourney,
  ctaTitle: 'Preview a premium physiotherapy contact flow.',
  ctaCopy: clinic => `${clinic.clinicName} can use this sample layout to make session inquiries feel direct and supportive.`,
};

export const diagnosticConfig = {
  shortLabel: 'Labs',
  businessType: 'diagnostic-center',
  businessLabel: 'diagnostic concept',
  navIcon: Microscope,
  heroIcon: TestTube2,
  miniIcon: FileText,
  miniLabel: 'Reports',
  appointmentTitle: 'Book a test',
  visualLabel: 'Diagnostics',
  colors: { accent: '#38bdf8', soft: '#f0f9ff', strong: '#0369a1', glow: 'rgba(125, 211, 252, 0.5)' },
  heroTitlePrefix: 'Modern diagnostic center concept for',
  heroTitleAccent: 'clearer test booking.',
  heroCopy: clinic => `${clinic.clinicName} is presented as a premium diagnostic-center preview for ${clinic.city}, focused on simple booking, clean information, and report-oriented navigation.`,
  heroBadges: ['Clear test categories', 'Report-focused navigation', 'Fast inquiry actions'],
  visualCards: ['Test booking hierarchy', 'Report collection cues', 'Calm lab-inspired visual system'],
  servicesTitle: 'Diagnostic sections built for clarity and quick scanning.',
  servicesCopy: 'The template focuses on booking and information flow, without making accuracy or turnaround claims.',
  services: [
    { title: 'Lab test booking', description: 'Simple structure for common diagnostic appointment inquiries.', icon: TestTube2 },
    { title: 'Imaging inquiries', description: 'Clear pathways for scan and imaging-related contact.', icon: ScanLine },
    { title: 'Report support', description: 'Helpful navigation for report collection and follow-up questions.', icon: FileText },
    { title: 'Health packages', description: 'A neutral way to organize package-style information.', icon: ClipboardCheck },
  ],
  trustTitle: 'A clean system for high-clarity diagnostic browsing.',
  trustCopy: 'Trust comes from organized information, measured language, and visible contact paths.',
  trustCards: [
    { kicker: 'Organization', title: 'Easy test discovery', copy: 'Cards keep test categories quick to understand.' },
    { kicker: 'Support', title: 'Report-oriented flow', copy: 'Visitors can see where report questions fit in the journey.' },
    { kicker: 'Neutrality', title: 'No performance claims', copy: 'The template avoids claims about accuracy or turnaround speed.' },
  ],
  journeyTitle: 'A simple path from test inquiry to report support.',
  journeyCopy: 'Designed for people who need clear diagnostic information without clutter.',
  journey: sharedJourney,
  ctaTitle: 'Preview a premium diagnostic booking flow.',
  ctaCopy: clinic => `This CTA layout helps ${clinic.clinicName} make test inquiries easier to start on mobile and desktop.`,
};

export const hospitalConfig = {
  shortLabel: 'Hospital',
  businessType: 'hospital',
  businessLabel: 'hospital concept',
  navIcon: Hospital,
  heroIcon: HeartPulse,
  miniIcon: Stethoscope,
  miniLabel: 'Departments',
  appointmentTitle: 'Plan a visit',
  visualLabel: 'Hospital Care',
  colors: { accent: '#60a5fa', soft: '#eff6ff', strong: '#1d4ed8', glow: 'rgba(147, 197, 253, 0.48)' },
  heroTitlePrefix: 'Premium hospital website concept for',
  heroTitleAccent: 'clearer care navigation.',
  heroCopy: clinic => `${clinic.clinicName} is shaped as a hospital homepage preview for ${clinic.city}, with clear department discovery, contact actions, and trust-focused structure.`,
  heroBadges: ['Department-led navigation', 'Visitor-friendly contact flow', 'Clear care pathways'],
  visualCards: ['Department discovery', 'Appointment and inquiry actions', 'Calm multi-specialty layout'],
  servicesTitle: 'Hospital sections that organize care without overwhelming visitors.',
  servicesCopy: 'The layout supports broad healthcare navigation while avoiding claims about outcomes or rankings.',
  services: [
    { title: 'Departments', description: 'A clean way to organize specialty and care-area navigation.', icon: Hospital },
    { title: 'Doctor inquiries', description: 'Clear entry points for appointment-related questions.', icon: Stethoscope },
    { title: 'Visitor support', description: 'Helpful placement for contact, location, and general guidance.', icon: Bed },
    { title: 'Emergency info area', description: 'A structured area for urgent-contact information if provided by the business.', icon: HeartPulse },
  ],
  trustTitle: 'A calm framework for larger healthcare decisions.',
  trustCopy: 'The template uses structure, clarity, and restraint instead of fake rankings or awards.',
  trustCards: [
    { kicker: 'Navigation', title: 'Department clarity', copy: 'Visitors can orient themselves quickly across care areas.' },
    { kicker: 'Access', title: 'Prominent contact paths', copy: 'Key inquiry options remain easy to find.' },
    { kicker: 'Restraint', title: 'No invented authority', copy: 'The page avoids unverified awards, ratings, and claims.' },
  ],
  journeyTitle: 'A clear route from hospital inquiry to visit planning.',
  journeyCopy: 'Designed to help visitors find the right next step without added friction.',
  journey: sharedJourney,
  ctaTitle: 'Preview a premium hospital inquiry experience.',
  ctaCopy: clinic => `This sample CTA style helps ${clinic.clinicName} guide visitors toward the right contact path.`,
};

export const ayurvedaConfig = {
  shortLabel: 'Ayurveda',
  businessType: 'ayurveda',
  businessLabel: 'ayurveda concept',
  navIcon: Leaf,
  heroIcon: Flower2,
  miniIcon: Leaf,
  miniLabel: 'Wellness',
  appointmentTitle: 'Request a consult',
  visualLabel: 'Ayurveda',
  colors: { accent: '#84cc16', soft: '#f7fee7', strong: '#4d7c0f', glow: 'rgba(190, 242, 100, 0.42)' },
  heroTitlePrefix: 'Premium Ayurveda website concept for',
  heroTitleAccent: 'calm wellness inquiries.',
  heroCopy: clinic => `${clinic.clinicName} is presented as a serene Ayurveda preview for ${clinic.city}, with soft wellness storytelling and easy consultation actions.`,
  heroBadges: ['Wellness-led tone', 'Calm consultation flow', 'Nature-inspired design'],
  visualCards: ['Holistic service organization', 'Soft green visual language', 'Clear consultation request actions'],
  servicesTitle: 'Ayurveda sections with a serene premium feel.',
  servicesCopy: 'The copy stays gentle and consultative without cure or outcome claims.',
  services: [
    { title: 'Ayurveda consultation', description: 'A calm starting point for appointment-led wellness inquiries.', icon: Leaf },
    { title: 'Lifestyle guidance', description: 'Measured content for routine and wellness conversations.', icon: SunMedium },
    { title: 'Therapy inquiries', description: 'A structured way to present therapy-related appointment topics.', icon: Flower2 },
    { title: 'Follow-up support', description: 'Simple next-step communication after a consultation request.', icon: ClipboardCheck },
  ],
  trustTitle: 'A wellness tone that feels calm and responsible.',
  trustCopy: 'The template emphasizes consultation, comfort, and clarity without cure claims.',
  trustCards: [
    { kicker: 'Tone', title: 'Gentle wellness language', copy: 'Copy is warm and respectful without medical overreach.' },
    { kicker: 'Design', title: 'Natural premium palette', copy: 'Soft green accents create a calm, clean identity.' },
    { kicker: 'Clarity', title: 'Easy appointment flow', copy: 'Visitors can request a consultation without confusion.' },
  ],
  journeyTitle: 'A calm path from wellness interest to consultation.',
  journeyCopy: 'A simple flow for visitors exploring Ayurveda and wellness support.',
  journey: sharedJourney,
  ctaTitle: 'Preview a premium Ayurveda consultation flow.',
  ctaCopy: clinic => `${clinic.clinicName} can use this sample CTA section to keep wellness inquiries simple and calm.`,
};

export const templateByBusinessType = {
  dentist: dentistConfig,
  dermatologist: dermatologyConfig,
  physiotherapy: physioConfig,
  'diagnostic-center': diagnosticConfig,
  hospital: hospitalConfig,
  ayurveda: ayurvedaConfig,
};
