import {
  Activity,
  Ambulance,
  CalendarDays,
  ClipboardCheck,
  Clock,
  Dumbbell,
  FlaskConical,
  Flower2,
  Heart,
  HeartPulse,
  Hospital,
  Leaf,
  Microscope,
  MoveRight,
  ScanFace,
  ShieldCheck,
  Smile,
  Sparkles,
  Stethoscope,
  Sun,
} from 'lucide-react';

export const dentistConfig = {
  shortLabel: 'Dental',
  businessType: 'dentist',
  businessLabel: 'bright dental studio concept',
  navIcon: Smile,
  heroIcon: Smile,
  miniIcon: CalendarDays,
  miniLabel: 'Dental consult',
  appointmentTitle: 'Book dental consultation',
  visualLabel: 'Dental Studio',
  colors: { accent: '#22d3ee', soft: '#ecfeff', strong: '#0e7490', glow: 'rgba(125, 211, 252, 0.48)' },
  heroTitlePrefix: 'Premium dental care concept for',
  heroTitleAccent: 'comfort-first smile journeys.',
  heroCopy: clinic => `${clinic.clinicName} is framed as a polished dental design preview for ${clinic.city}, with bright spacing, simple contact paths, and reassuring visit guidance.`,
  heroBadges: ['Smile-focused visit flow', 'Bright dental studio feel', 'Comfort-first guidance'],
  visualCards: ['Dental implants and aligner sections', 'Root canal and whitening inquiry paths', 'Mobile-first call and WhatsApp actions'],
  servicesTitle: 'Dental services presented with clarity and calm.',
  servicesCopy: 'A refined structure for dental implants, aligners, root canal, whitening, and consultation topics without promising outcomes.',
  services: [
    { title: 'Dental implants', description: 'A premium consultation path for restorative dental inquiries.', icon: Smile },
    { title: 'Aligners', description: 'Clear guidance for smile alignment conversations.', icon: Sparkles },
    { title: 'Root canal', description: 'Measured copy for treatment planning without outcome promises.', icon: ShieldCheck },
    { title: 'Whitening', description: 'A polished way to present cosmetic dental interest.', icon: CalendarDays },
  ],
  trustTitle: 'Dental trust built through clarity and comfort.',
  trustCopy: 'Trust cues describe the page experience itself and avoid ratings, outcomes, awards, or patient-volume claims.',
  trustCards: [
    { kicker: 'Comfort', title: 'Calm appointment flow', copy: 'Visitors can see how to contact the clinic without pressure.' },
    { kicker: 'Clarity', title: 'Treatment topics, not claims', copy: 'Services stay consultation-led and avoid guaranteed outcomes.' },
    { kicker: 'Access', title: 'Mobile-ready contact', copy: 'Call and WhatsApp actions are easy to find on every screen size.' },
  ],
  journeyTitle: 'A simple path from dental inquiry to next steps.',
  journeyCopy: 'Simple steps designed for comfort and clarity, with a polished clinic experience.',
  journey: [
    { title: 'Call or WhatsApp', copy: 'Request a convenient dental consultation time.', icon: CalendarDays },
    { title: 'Share concern', copy: 'Provide basic context about the dental visit.', icon: Smile },
    { title: 'Visit studio', copy: 'Arrive for a clear and calm clinic experience.', icon: ShieldCheck },
    { title: 'Review next steps', copy: 'Leave with simple follow-up information.', icon: Sparkles },
  ],
  ctaTitle: 'Preview a premium dental consultation flow.',
  ctaCopy: clinic => `This sample keeps outreach direct with prominent contact actions for ${clinic.clinicName} in ${clinic.city}.`,
};

export const dermatologyConfig = {
  shortLabel: 'Derma',
  businessType: 'dermatologist',
  businessLabel: 'soft skin clinic concept',
  navIcon: Sparkles,
  heroIcon: ScanFace,
  miniIcon: Sparkles,
  miniLabel: 'Skin consult',
  appointmentTitle: 'Book skin consultation',
  visualLabel: 'Dermatology',
  colors: { accent: '#c084fc', soft: '#faf5ff', strong: '#7e22ce', glow: 'rgba(216, 180, 254, 0.46)' },
  heroTitlePrefix: 'Modern dermatology concept for',
  heroTitleAccent: 'clearer skin-care conversations.',
  heroCopy: clinic => `${clinic.clinicName} is presented as a premium dermatology design preview for ${clinic.city}, focused on soft visual hierarchy, discretion, and consultation-led copy.`,
  heroBadges: ['Skin consultation framing', 'Beauty plus medical trust', 'Private, measured copy'],
  visualCards: ['Acne care and skin consultation sections', 'Laser and anti-aging inquiry paths', 'Soft rose and lavender visual system'],
  servicesTitle: 'Skin-clinic sections with a calm editorial feel.',
  servicesCopy: 'Service areas are framed as consultation topics, avoiding before-and-after promises or outcome claims.',
  services: [
    { title: 'Acne care', description: 'A clear entry point for acne-related consultation inquiries.', icon: Sparkles },
    { title: 'Laser treatment', description: 'Premium framing for laser treatment conversations.', icon: ScanFace },
    { title: 'Anti-aging', description: 'Careful language for age-related skin-care interest.', icon: ShieldCheck },
    { title: 'Skin consultation', description: 'A calm pathway for first-time dermatology visitors.', icon: HeartPulse },
  ],
  trustTitle: 'A private, premium tone for skin-care decisions.',
  trustCopy: 'The template emphasizes clarity, discretion, and careful language instead of dramatic transformations.',
  trustCards: [
    { kicker: 'Privacy', title: 'Composed patient flow', copy: 'The design avoids sensational visuals and keeps the experience calm.' },
    { kicker: 'Restraint', title: 'No before-after promises', copy: 'Language stays consultative instead of outcome-driven.' },
    { kicker: 'Guidance', title: 'Easy skin consult path', copy: 'Prominent CTAs support quick inquiry without feeling aggressive.' },
  ],
  journeyTitle: 'A calm route from skin concern to consultation.',
  journeyCopy: 'The patient journey is designed for sensitive, question-led dermatology browsing.',
  journey: [
    { title: 'Request consult', copy: 'Start with a simple skin consultation inquiry.', icon: CalendarDays },
    { title: 'Share concern', copy: 'Provide basic context around the skin-care topic.', icon: ScanFace },
    { title: 'Visit clinic', copy: 'Arrive for a guided dermatology conversation.', icon: ShieldCheck },
    { title: 'Receive guidance', copy: 'Leave with clear next-step information.', icon: HeartPulse },
  ],
  ctaTitle: 'Create a calmer dermatology inquiry experience.',
  ctaCopy: clinic => `Use this sample CTA style for ${clinic.clinicName} to make skin consultation inquiries feel simple and respectful.`,
};

export const physioConfig = {
  shortLabel: 'Physio',
  businessType: 'physiotherapy',
  businessLabel: 'movement recovery concept',
  navIcon: Dumbbell,
  heroIcon: Activity,
  miniIcon: MoveRight,
  miniLabel: 'Recovery plan',
  appointmentTitle: 'Start recovery plan',
  visualLabel: 'Physiotherapy',
  colors: { accent: '#34d399', soft: '#ecfdf5', strong: '#047857', glow: 'rgba(110, 231, 183, 0.46)' },
  heroTitlePrefix: 'Premium physiotherapy concept for',
  heroTitleAccent: 'guided movement support.',
  heroCopy: clinic => `${clinic.clinicName} is shaped as a clean physiotherapy preview for ${clinic.city}, with approachable visit planning and practical recovery-focused content.`,
  heroBadges: ['Movement-led visit flow', 'Recovery-focused sections', 'Posture and rehab tone'],
  visualCards: ['Spine therapy and posture sections', 'Sports injury and rehab inquiry paths', 'Active green recovery visual system'],
  servicesTitle: 'Physiotherapy sections with movement, clarity, and care.',
  servicesCopy: 'Copy is framed around support and guidance without claiming recovery guarantees.',
  services: [
    { title: 'Spine therapy', description: 'A supportive section for spine and mobility-related inquiries.', icon: Activity },
    { title: 'Sports injury', description: 'Responsible framing for sports injury rehab interest.', icon: Dumbbell },
    { title: 'Posture correction', description: 'Practical content for posture and workplace movement concerns.', icon: HeartPulse },
    { title: 'Rehab', description: 'A clear pathway for guided rehabilitation conversations.', icon: MoveRight },
  ],
  trustTitle: 'Recovery support presented with practical clarity.',
  trustCopy: 'The template feels active and reassuring without promising recovery timelines or results.',
  trustCards: [
    { kicker: 'Movement', title: 'Active visual language', copy: 'Cards and icons communicate motion without over-animation.' },
    { kicker: 'Support', title: 'Plain next steps', copy: 'Visitors can understand how to request a session.' },
    { kicker: 'Care', title: 'Responsible rehab copy', copy: 'The page avoids recovery guarantees and inflated claims.' },
  ],
  journeyTitle: 'A practical path from inquiry to guided movement.',
  journeyCopy: 'A mobile-friendly structure for visitors looking for physiotherapy support.',
  journey: [
    { title: 'Connect', copy: 'Request a convenient physiotherapy session.', icon: CalendarDays },
    { title: 'Share goals', copy: 'Describe movement, posture, or recovery needs.', icon: Activity },
    { title: 'Attend session', copy: 'Arrive for a guided movement conversation.', icon: Dumbbell },
    { title: 'Plan follow-up', copy: 'Review practical next-step information.', icon: MoveRight },
  ],
  ctaTitle: 'Preview a premium physiotherapy contact flow.',
  ctaCopy: clinic => `${clinic.clinicName} can use this sample layout to make session inquiries feel direct and supportive.`,
};

export const diagnosticConfig = {
  shortLabel: 'Labs',
  businessType: 'diagnostic-center',
  businessLabel: 'precision lab concept',
  navIcon: Microscope,
  heroIcon: FlaskConical,
  miniIcon: ClipboardCheck,
  miniLabel: 'Reports',
  appointmentTitle: 'Book health checkup',
  visualLabel: 'Diagnostics',
  colors: { accent: '#38bdf8', soft: '#f0f9ff', strong: '#0369a1', glow: 'rgba(125, 211, 252, 0.5)' },
  heroTitlePrefix: 'Modern diagnostic center concept for',
  heroTitleAccent: 'clearer test booking.',
  heroCopy: clinic => `${clinic.clinicName} is presented as a premium diagnostic-center preview for ${clinic.city}, focused on simple booking, clean information, and report-oriented navigation.`,
  heroBadges: ['Lab-report navigation', 'Precision-inspired layout', 'Fast booking path'],
  visualCards: ['Blood tests and package hierarchy', 'Imaging and report support cues', 'Light blue and indigo lab style'],
  servicesTitle: 'Diagnostic sections built for clarity and quick scanning.',
  servicesCopy: 'The template focuses on booking and information flow, without making accuracy or turnaround claims.',
  services: [
    { title: 'Blood tests', description: 'A clean pathway for common blood test inquiries.', icon: FlaskConical },
    { title: 'Health packages', description: 'Organized package-style information without performance claims.', icon: Microscope },
    { title: 'Imaging', description: 'Clear navigation for imaging and scan-related questions.', icon: ClipboardCheck },
    { title: 'Same-day reports', description: 'Report-oriented flow presented without turnaround promises.', icon: Clock },
  ],
  trustTitle: 'Diagnostic browsing designed for quick understanding.',
  trustCopy: 'Trust comes from organized information, measured language, and visible contact paths.',
  trustCards: [
    { kicker: 'Precision', title: 'Lab-inspired structure', copy: 'Information is grouped for quick scanning.' },
    { kicker: 'Reports', title: 'Clear support flow', copy: 'Visitors can see where report questions fit.' },
    { kicker: 'Neutrality', title: 'No performance claims', copy: 'Copy avoids unverifiable speed or accuracy promises.' },
  ],
  journeyTitle: 'A simple path from test inquiry to report support.',
  journeyCopy: 'Designed for people who need clear diagnostic information without clutter.',
  journey: [
    { title: 'Choose test', copy: 'Browse test or package topics.', icon: FlaskConical },
    { title: 'Book slot', copy: 'Use the contact action to request a time.', icon: CalendarDays },
    { title: 'Visit center', copy: 'Arrive for the diagnostic appointment.', icon: Microscope },
    { title: 'Access reports', copy: 'Find report support information clearly.', icon: ClipboardCheck },
  ],
  ctaTitle: 'Preview a premium diagnostic booking flow.',
  ctaCopy: clinic => `This CTA layout helps ${clinic.clinicName} make test inquiries easier to start on mobile and desktop.`,
};

export const hospitalConfig = {
  shortLabel: 'Hospital',
  businessType: 'hospital',
  businessLabel: 'multi-specialty care concept',
  navIcon: Hospital,
  heroIcon: Hospital,
  miniIcon: Stethoscope,
  miniLabel: 'Departments',
  appointmentTitle: 'Book appointment',
  visualLabel: 'Hospital Care',
  colors: { accent: '#14b8a6', soft: '#f0fdfa', strong: '#0f766e', glow: 'rgba(45, 212, 191, 0.36)' },
  heroTitlePrefix: 'Premium hospital website concept for',
  heroTitleAccent: 'clearer care navigation.',
  heroCopy: clinic => `${clinic.clinicName} is shaped as a hospital homepage preview for ${clinic.city}, with clear department discovery, contact actions, and trust-focused structure.`,
  heroBadges: ['Multi-specialty structure', 'Emergency-ready information area', 'Trusted care navigation'],
  visualCards: ['OPD and specialist care sections', 'Emergency and surgery inquiry paths', 'Premium navy and teal healthcare style'],
  servicesTitle: 'Hospital sections that organize care without overwhelming visitors.',
  servicesCopy: 'The layout supports broad healthcare navigation while avoiding claims about outcomes or rankings.',
  services: [
    { title: 'OPD', description: 'A clear outpatient discovery section for appointment-led browsing.', icon: Hospital },
    { title: 'Emergency', description: 'Structured urgent-contact information if provided by the business.', icon: Ambulance },
    { title: 'Surgery', description: 'Careful framing for procedure-related inquiry pathways.', icon: Stethoscope },
    { title: 'Specialist care', description: 'Easy navigation for specialist consultation interest.', icon: ShieldCheck },
  ],
  trustTitle: 'A clear structure for healthcare decisions.',
  trustCopy: 'The template uses navigation, clarity, and restraint instead of fake rankings or awards.',
  trustCards: [
    { kicker: 'Navigation', title: 'Department clarity', copy: 'Visitors can orient themselves quickly across care areas.' },
    { kicker: 'Access', title: 'Prominent contact paths', copy: 'Key inquiry options remain easy to find.' },
    { kicker: 'Restraint', title: 'No invented authority', copy: 'The page avoids unverified awards, ratings, and claims.' },
  ],
  journeyTitle: 'A clear route from hospital inquiry to visit planning.',
  journeyCopy: 'Designed to help visitors find the right next step without added friction.',
  journey: [
    { title: 'Explore care', copy: 'Browse broad care and department topics.', icon: Hospital },
    { title: 'Contact desk', copy: 'Use call or WhatsApp to request guidance.', icon: Stethoscope },
    { title: 'Plan visit', copy: 'Confirm basic appointment or visit details.', icon: CalendarDays },
    { title: 'Follow guidance', copy: 'Review the next-step information provided.', icon: ShieldCheck },
  ],
  ctaTitle: 'Preview a premium hospital inquiry experience.',
  ctaCopy: clinic => `This sample CTA style helps ${clinic.clinicName} guide visitors toward the right contact path.`,
};

export const ayurvedaConfig = {
  shortLabel: 'Ayurveda',
  businessType: 'ayurveda',
  businessLabel: 'natural wellness concept',
  navIcon: Leaf,
  heroIcon: Flower2,
  miniIcon: Leaf,
  miniLabel: 'Wellness',
  appointmentTitle: 'Book wellness consultation',
  visualLabel: 'Ayurveda',
  colors: { accent: '#84cc16', soft: '#f7fee7', strong: '#4d7c0f', glow: 'rgba(254, 215, 170, 0.48)' },
  heroTitlePrefix: 'Premium Ayurveda website concept for',
  heroTitleAccent: 'calm wellness inquiries.',
  heroCopy: clinic => `${clinic.clinicName} is presented as a serene Ayurveda preview for ${clinic.city}, with soft wellness storytelling and easy consultation actions.`,
  heroBadges: ['Natural wellness tone', 'Warm heritage-inspired palette', 'Calm consultation flow'],
  visualCards: ['Panchakarma and wellness sections', 'Stress care and immunity inquiry paths', 'Warm cream, green, and amber natural style'],
  servicesTitle: 'Ayurveda sections with a serene premium feel.',
  servicesCopy: 'The copy stays gentle and consultative without cure or outcome claims.',
  services: [
    { title: 'Panchakarma', description: 'A serene way to present Panchakarma-related consultation interest.', icon: Leaf },
    { title: 'Stress care', description: 'Gentle copy for stress and lifestyle-support conversations.', icon: Flower2 },
    { title: 'Immunity', description: 'Wellness framing that avoids cure or outcome claims.', icon: Heart },
    { title: 'Wellness consultation', description: 'A clear entry point for Ayurveda consultation requests.', icon: Sun },
  ],
  trustTitle: 'A calm wellness tone with responsible copy.',
  trustCopy: 'The template emphasizes consultation, comfort, and clarity without cure claims.',
  trustCards: [
    { kicker: 'Calm', title: 'Nature-inspired design', copy: 'Warm gradients and soft cards create a grounded experience.' },
    { kicker: 'Responsibility', title: 'No cure claims', copy: 'Copy remains careful and consultation-led.' },
    { kicker: 'Clarity', title: 'Easy appointment flow', copy: 'Visitors can request a consultation without confusion.' },
  ],
  journeyTitle: 'A calm path from wellness interest to consultation.',
  journeyCopy: 'A simple flow for visitors exploring Ayurveda and wellness support.',
  journey: [
    { title: 'Request consult', copy: 'Start with a simple wellness consultation inquiry.', icon: CalendarDays },
    { title: 'Share goals', copy: 'Provide lifestyle or wellness context.', icon: Leaf },
    { title: 'Visit clinic', copy: 'Arrive for a calm consultation conversation.', icon: Flower2 },
    { title: 'Review guidance', copy: 'Leave with clear next-step information.', icon: Sun },
  ],
  ctaTitle: 'Preview a premium Ayurveda consultation flow.',
  ctaCopy: clinic => `${clinic.clinicName} can use this sample CTA section to keep wellness inquiries simple and calm.`,
};

export const templateByBusinessType = {
  dentist: dentistConfig,
  dermatologist: dermatologyConfig,
  physiotherapy: physioConfig,
  'diagnostic-center': diagnosticConfig,
  hospital: hospitalConfig,
  ayurveda: ayurvedaConfig,
};
